apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: himanshuapp
  name: himanshuapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: himanshuapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: himanshuapp
    spec:
      containers:
      - image: dockerashu/jecrcapp:v1
        name: jecrcapp
        ports:
        - containerPort: 80
        resources: {}
status: {}
