apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: himanshuapp
  name: himanshuapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: himanshuapp
  type: NodePort
status:
  loadBalancer: {}
